export const LocalNavItems=[
    {
        key:"PrincipalInNavMenu",
        link:"/",
        caption:"Principal"
    },
    {
        key:"WorksInNavMenu",
        link:"/works",
        caption:"Trabajos"
    },
    {
        key:"DesingsInNavMenu",
        link:"/sketches",
        caption:"Bocetos"
    },
    {
        key:"HealtInNavMenu",
        link:"/hygiene",
        caption:"Higiene"
    },
    {
        key:"TatuadorInNavMenu",
        link:"/artist",
        caption:"Artista"  
    }
]